### ISSUE TITLE
Sample rate options?

### ISSUE THREAD

**Issue by swrobel** [fzao/pLACaudio#1]
This app is amazing and is almost exactly what I was looking for to convert my collection of ripped SACDs to FLAC. However, it seems I can't control the sample rate of the resulting FLAC, unless I'm missing something.

**Comment by fzao** [comment]
Hello swrobel and thanks for your feedback. I keep your remark as a possible future development (resampling).

**Comment by fzao** [comment]
New version 0.4 is out with the possibility to choose sample rate as requested.

Enjoy!
