### ISSUE TITLE
Converting WAV to AIFF - no loop info?

### ISSUE THREAD

**Issue by jtl3d** [fzao/pLACaudio#2]
Forgive me, I'm a bit uneducated on audio, but I am trying to convert WAV files to AIFF and this tool works great. However, I'm not sure if the looping info embedded in the WAV is getting embedded in the resulting AIFF, or if that's even possible. Can you tell me if I'm doing something wrong, making bad assumptions, or being too unclear?

Thanks!

**Comment by fzao** [comment]
Hello, can you tell me please what do mean by "looping info" ?

Regards

**Comment by jtl3d** [comment]
That's a good question. The end goal is a sample that is used as an instrument sound in a MIDI. I assume loop info tells the MIDI how to sustain longer notes. My understanding is that loop start, end and count can be embedded in the WAV, but I don't know enough about that side of it to be certain. Any of this make sense?

**Comment by fzao** [comment]
You're right. As far as I can see loop points can be present in two different chunks in a wav file (CUE or SMPL). But I did not find the corresponding information with the description of the AIFF format? As pLACaudio uses 'ffmpeg' to convert files with the option of keeping the metadata, may be it could do the job? Please let me know if you can do such a test.

Thanks

**Comment by fzao** [comment]
Oh I see but I did not do any test about this. As pLACaudio uses 'ffmpeg' to convert files with the option of keeping the metadata, may be it could do the job? Please let me know if you can do such a test.

Thanks

**Comment by jtl3d** [comment]
Sorry couldn't do a test. Thanks again.
